[package]
name = "bvid"
version = "1.0.0"
edition = "2021"
authors = ["stackinspector"]
license = "MIT"
repository = "https://github.com/stackinspector/bvid"

[lib]
path = "lib.rs"

[features]
arraystr = []
